/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Empresa
 */
public class EmpresaTest {
    private final Empresa model = new Empresa();

    /**
     * Model tests for Empresa
     */
    @Test
    public void testEmpresa() {
        // TODO: test Empresa
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nombreEmpresa'
     */
    @Test
    public void nombreEmpresaTest() {
        // TODO: test nombreEmpresa
    }

    /**
     * Test the property 'tutorLaboralNombre'
     */
    @Test
    public void tutorLaboralNombreTest() {
        // TODO: test tutorLaboralNombre
    }

    /**
     * Test the property 'tutorLaboralEmail'
     */
    @Test
    public void tutorLaboralEmailTest() {
        // TODO: test tutorLaboralEmail
    }

    /**
     * Test the property 'tutorLaboralTelefono'
     */
    @Test
    public void tutorLaboralTelefonoTest() {
        // TODO: test tutorLaboralTelefono
    }

    /**
     * Test the property 'activo'
     */
    @Test
    public void activoTest() {
        // TODO: test activo
    }

}
