/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UsuarioDTO
 */
public class UsuarioDTOTest {
    private final UsuarioDTO model = new UsuarioDTO();

    /**
     * Model tests for UsuarioDTO
     */
    @Test
    public void testUsuarioDTO() {
        // TODO: test UsuarioDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nombreCompleto'
     */
    @Test
    public void nombreCompletoTest() {
        // TODO: test nombreCompleto
    }

    /**
     * Test the property 'tutorDocente'
     */
    @Test
    public void tutorDocenteTest() {
        // TODO: test tutorDocente
    }

    /**
     * Test the property 'ciclo'
     */
    @Test
    public void cicloTest() {
        // TODO: test ciclo
    }

    /**
     * Test the property 'año'
     */
    @Test
    public void añoTest() {
        // TODO: test año
    }

    /**
     * Test the property 'evaluacion'
     */
    @Test
    public void evaluacionTest() {
        // TODO: test evaluacion
    }

    /**
     * Test the property 'docente'
     */
    @Test
    public void docenteTest() {
        // TODO: test docente
    }

    /**
     * Test the property 'empresaAsignada'
     */
    @Test
    public void empresaAsignadaTest() {
        // TODO: test empresaAsignada
    }

    /**
     * Test the property 'cantidadHoras'
     */
    @Test
    public void cantidadHorasTest() {
        // TODO: test cantidadHoras
    }

}
