/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * FechaPractica
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-15T17:50:53.660208200+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class FechaPractica {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_FECHA = "fecha";
  @SerializedName(SERIALIZED_NAME_FECHA)
  @javax.annotation.Nullable
  private LocalDate fecha;

  public static final String SERIALIZED_NAME_ANIO_CURSO = "anioCurso";
  @SerializedName(SERIALIZED_NAME_ANIO_CURSO)
  @javax.annotation.Nullable
  private Integer anioCurso;

  public static final String SERIALIZED_NAME_EVALUACION = "evaluacion";
  @SerializedName(SERIALIZED_NAME_EVALUACION)
  @javax.annotation.Nullable
  private String evaluacion;

  public FechaPractica() {
  }

  public FechaPractica id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public FechaPractica fecha(@javax.annotation.Nullable LocalDate fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * Get fecha
   * @return fecha
   */
  @javax.annotation.Nullable
  public LocalDate getFecha() {
    return fecha;
  }

  public void setFecha(@javax.annotation.Nullable LocalDate fecha) {
    this.fecha = fecha;
  }


  public FechaPractica anioCurso(@javax.annotation.Nullable Integer anioCurso) {
    this.anioCurso = anioCurso;
    return this;
  }

  /**
   * Get anioCurso
   * @return anioCurso
   */
  @javax.annotation.Nullable
  public Integer getAnioCurso() {
    return anioCurso;
  }

  public void setAnioCurso(@javax.annotation.Nullable Integer anioCurso) {
    this.anioCurso = anioCurso;
  }


  public FechaPractica evaluacion(@javax.annotation.Nullable String evaluacion) {
    this.evaluacion = evaluacion;
    return this;
  }

  /**
   * Get evaluacion
   * @return evaluacion
   */
  @javax.annotation.Nullable
  public String getEvaluacion() {
    return evaluacion;
  }

  public void setEvaluacion(@javax.annotation.Nullable String evaluacion) {
    this.evaluacion = evaluacion;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FechaPractica fechaPractica = (FechaPractica) o;
    return Objects.equals(this.id, fechaPractica.id) &&
        Objects.equals(this.fecha, fechaPractica.fecha) &&
        Objects.equals(this.anioCurso, fechaPractica.anioCurso) &&
        Objects.equals(this.evaluacion, fechaPractica.evaluacion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, fecha, anioCurso, evaluacion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FechaPractica {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fecha: ").append(toIndentedString(fecha)).append("\n");
    sb.append("    anioCurso: ").append(toIndentedString(anioCurso)).append("\n");
    sb.append("    evaluacion: ").append(toIndentedString(evaluacion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("fecha");
    openapiFields.add("anioCurso");
    openapiFields.add("evaluacion");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FechaPractica
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FechaPractica.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FechaPractica is not found in the empty JSON string", FechaPractica.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FechaPractica.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FechaPractica` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("evaluacion") != null && !jsonObj.get("evaluacion").isJsonNull()) && !jsonObj.get("evaluacion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `evaluacion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("evaluacion").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FechaPractica.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FechaPractica' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FechaPractica> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FechaPractica.class));

       return (TypeAdapter<T>) new TypeAdapter<FechaPractica>() {
           @Override
           public void write(JsonWriter out, FechaPractica value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FechaPractica read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FechaPractica given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FechaPractica
   * @throws IOException if the JSON string is invalid with respect to FechaPractica
   */
  public static FechaPractica fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FechaPractica.class);
  }

  /**
   * Convert an instance of FechaPractica to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

