/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UsuarioDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-15T17:50:53.660208200+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class UsuarioDTO {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_NOMBRE_COMPLETO = "nombreCompleto";
  @SerializedName(SERIALIZED_NAME_NOMBRE_COMPLETO)
  @javax.annotation.Nullable
  private String nombreCompleto;

  public static final String SERIALIZED_NAME_TUTOR_DOCENTE = "tutorDocente";
  @SerializedName(SERIALIZED_NAME_TUTOR_DOCENTE)
  @javax.annotation.Nullable
  private String tutorDocente;

  public static final String SERIALIZED_NAME_CICLO = "ciclo";
  @SerializedName(SERIALIZED_NAME_CICLO)
  @javax.annotation.Nullable
  private String ciclo;

  public static final String SERIALIZED_NAME_AñO = "año";
  @SerializedName(SERIALIZED_NAME_AñO)
  @javax.annotation.Nullable
  private Integer año;

  public static final String SERIALIZED_NAME_EVALUACION = "evaluacion";
  @SerializedName(SERIALIZED_NAME_EVALUACION)
  @javax.annotation.Nullable
  private String evaluacion;

  public static final String SERIALIZED_NAME_DOCENTE = "docente";
  @SerializedName(SERIALIZED_NAME_DOCENTE)
  @javax.annotation.Nullable
  private String docente;

  public static final String SERIALIZED_NAME_EMPRESA_ASIGNADA = "empresaAsignada";
  @SerializedName(SERIALIZED_NAME_EMPRESA_ASIGNADA)
  @javax.annotation.Nullable
  private String empresaAsignada;

  public static final String SERIALIZED_NAME_CANTIDAD_HORAS = "cantidadHoras";
  @SerializedName(SERIALIZED_NAME_CANTIDAD_HORAS)
  @javax.annotation.Nullable
  private Integer cantidadHoras;

  public UsuarioDTO() {
  }

  public UsuarioDTO id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public UsuarioDTO nombreCompleto(@javax.annotation.Nullable String nombreCompleto) {
    this.nombreCompleto = nombreCompleto;
    return this;
  }

  /**
   * Get nombreCompleto
   * @return nombreCompleto
   */
  @javax.annotation.Nullable
  public String getNombreCompleto() {
    return nombreCompleto;
  }

  public void setNombreCompleto(@javax.annotation.Nullable String nombreCompleto) {
    this.nombreCompleto = nombreCompleto;
  }


  public UsuarioDTO tutorDocente(@javax.annotation.Nullable String tutorDocente) {
    this.tutorDocente = tutorDocente;
    return this;
  }

  /**
   * Get tutorDocente
   * @return tutorDocente
   */
  @javax.annotation.Nullable
  public String getTutorDocente() {
    return tutorDocente;
  }

  public void setTutorDocente(@javax.annotation.Nullable String tutorDocente) {
    this.tutorDocente = tutorDocente;
  }


  public UsuarioDTO ciclo(@javax.annotation.Nullable String ciclo) {
    this.ciclo = ciclo;
    return this;
  }

  /**
   * Get ciclo
   * @return ciclo
   */
  @javax.annotation.Nullable
  public String getCiclo() {
    return ciclo;
  }

  public void setCiclo(@javax.annotation.Nullable String ciclo) {
    this.ciclo = ciclo;
  }


  public UsuarioDTO año(@javax.annotation.Nullable Integer año) {
    this.año = año;
    return this;
  }

  /**
   * Get año
   * @return año
   */
  @javax.annotation.Nullable
  public Integer getAño() {
    return año;
  }

  public void setAño(@javax.annotation.Nullable Integer año) {
    this.año = año;
  }


  public UsuarioDTO evaluacion(@javax.annotation.Nullable String evaluacion) {
    this.evaluacion = evaluacion;
    return this;
  }

  /**
   * Get evaluacion
   * @return evaluacion
   */
  @javax.annotation.Nullable
  public String getEvaluacion() {
    return evaluacion;
  }

  public void setEvaluacion(@javax.annotation.Nullable String evaluacion) {
    this.evaluacion = evaluacion;
  }


  public UsuarioDTO docente(@javax.annotation.Nullable String docente) {
    this.docente = docente;
    return this;
  }

  /**
   * Get docente
   * @return docente
   */
  @javax.annotation.Nullable
  public String getDocente() {
    return docente;
  }

  public void setDocente(@javax.annotation.Nullable String docente) {
    this.docente = docente;
  }


  public UsuarioDTO empresaAsignada(@javax.annotation.Nullable String empresaAsignada) {
    this.empresaAsignada = empresaAsignada;
    return this;
  }

  /**
   * Get empresaAsignada
   * @return empresaAsignada
   */
  @javax.annotation.Nullable
  public String getEmpresaAsignada() {
    return empresaAsignada;
  }

  public void setEmpresaAsignada(@javax.annotation.Nullable String empresaAsignada) {
    this.empresaAsignada = empresaAsignada;
  }


  public UsuarioDTO cantidadHoras(@javax.annotation.Nullable Integer cantidadHoras) {
    this.cantidadHoras = cantidadHoras;
    return this;
  }

  /**
   * Get cantidadHoras
   * @return cantidadHoras
   */
  @javax.annotation.Nullable
  public Integer getCantidadHoras() {
    return cantidadHoras;
  }

  public void setCantidadHoras(@javax.annotation.Nullable Integer cantidadHoras) {
    this.cantidadHoras = cantidadHoras;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsuarioDTO usuarioDTO = (UsuarioDTO) o;
    return Objects.equals(this.id, usuarioDTO.id) &&
        Objects.equals(this.nombreCompleto, usuarioDTO.nombreCompleto) &&
        Objects.equals(this.tutorDocente, usuarioDTO.tutorDocente) &&
        Objects.equals(this.ciclo, usuarioDTO.ciclo) &&
        Objects.equals(this.año, usuarioDTO.año) &&
        Objects.equals(this.evaluacion, usuarioDTO.evaluacion) &&
        Objects.equals(this.docente, usuarioDTO.docente) &&
        Objects.equals(this.empresaAsignada, usuarioDTO.empresaAsignada) &&
        Objects.equals(this.cantidadHoras, usuarioDTO.cantidadHoras);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nombreCompleto, tutorDocente, ciclo, año, evaluacion, docente, empresaAsignada, cantidadHoras);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsuarioDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nombreCompleto: ").append(toIndentedString(nombreCompleto)).append("\n");
    sb.append("    tutorDocente: ").append(toIndentedString(tutorDocente)).append("\n");
    sb.append("    ciclo: ").append(toIndentedString(ciclo)).append("\n");
    sb.append("    año: ").append(toIndentedString(año)).append("\n");
    sb.append("    evaluacion: ").append(toIndentedString(evaluacion)).append("\n");
    sb.append("    docente: ").append(toIndentedString(docente)).append("\n");
    sb.append("    empresaAsignada: ").append(toIndentedString(empresaAsignada)).append("\n");
    sb.append("    cantidadHoras: ").append(toIndentedString(cantidadHoras)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("nombreCompleto");
    openapiFields.add("tutorDocente");
    openapiFields.add("ciclo");
    openapiFields.add("año");
    openapiFields.add("evaluacion");
    openapiFields.add("docente");
    openapiFields.add("empresaAsignada");
    openapiFields.add("cantidadHoras");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UsuarioDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UsuarioDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UsuarioDTO is not found in the empty JSON string", UsuarioDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UsuarioDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UsuarioDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nombreCompleto") != null && !jsonObj.get("nombreCompleto").isJsonNull()) && !jsonObj.get("nombreCompleto").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nombreCompleto` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nombreCompleto").toString()));
      }
      if ((jsonObj.get("tutorDocente") != null && !jsonObj.get("tutorDocente").isJsonNull()) && !jsonObj.get("tutorDocente").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tutorDocente` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tutorDocente").toString()));
      }
      if ((jsonObj.get("ciclo") != null && !jsonObj.get("ciclo").isJsonNull()) && !jsonObj.get("ciclo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ciclo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ciclo").toString()));
      }
      if ((jsonObj.get("evaluacion") != null && !jsonObj.get("evaluacion").isJsonNull()) && !jsonObj.get("evaluacion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `evaluacion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("evaluacion").toString()));
      }
      if ((jsonObj.get("docente") != null && !jsonObj.get("docente").isJsonNull()) && !jsonObj.get("docente").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `docente` to be a primitive type in the JSON string but got `%s`", jsonObj.get("docente").toString()));
      }
      if ((jsonObj.get("empresaAsignada") != null && !jsonObj.get("empresaAsignada").isJsonNull()) && !jsonObj.get("empresaAsignada").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `empresaAsignada` to be a primitive type in the JSON string but got `%s`", jsonObj.get("empresaAsignada").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UsuarioDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UsuarioDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UsuarioDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UsuarioDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<UsuarioDTO>() {
           @Override
           public void write(JsonWriter out, UsuarioDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UsuarioDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UsuarioDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UsuarioDTO
   * @throws IOException if the JSON string is invalid with respect to UsuarioDTO
   */
  public static UsuarioDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UsuarioDTO.class);
  }

  /**
   * Convert an instance of UsuarioDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

